import { prisma } from '../lib/prisma.js';

const interestsData = [
  '3D printing',
  'Acting',
  'Air sports',
  'Aircraft spotting',
  'Airsoft',
  'Amateur astronomy',
  'Animal fancy',
  'Anime figurine collecting',
  'Antiquing',
  'Antiquities',
  'Archery',
  'Art collecting',
  'Association football',
  'Astronomy',
  'Audiophile',
  'Auto audiophilia',
  'Auto racing',
  'Autograph collecting',
  'Australian rules football',
  'Badminton',
  'BASE jumping',
  'Baseball',
  'Basketball',
  'Baton twirling',
  'Beach volleyball',
  'Beauty pageants',
  'Beekeeping',
  'Billiards',
  'Birdwatching',
  'BMX',
  'Board sports',
  'Board/tabletop games',
  'Bodybuilding',
  'Bonsai',
  'Book collecting',
  'Book discussion clubs',
  'Bowling',
  'Boxing',
  'Brazilian jiu-jitsu',
  'Breakdancing',
  'Bridge',
  'Bus spotting',
  'Candle making',
  'Cartophily (card collecting)',
  'Cheerleading',
  'Chess',
  'Climbing',
  'Coin collecting',
  'Coloring',
  'Color guard',
  'Comic book collecting',
  'Computer programming',
  'Cooking',
  'Cosplaying',
  'Creative writing',
  'Cricket',
  'Cryptography',
  'Curling',
  'Cycling',
  'Dance',
  'Dancing',
  'Dandyism',
  'Darts',
  'Debate',
  'Deltiology (postcard collecting)',
  'Digital arts',
  'Disc golf',
  'Do it yourself',
  'Dog sport',
  'Dowsing',
  'Drama',
  'Drawing',
  'Driving',
  'Element collecting',
  'Electronics',
  'Embroidery',
  'Equestrianism',
  'Exhibition drill',
  'Fencing',
  'Field hockey',
  'Figure skating',
  'Fishing',
  'Flag football',
  'Flower arranging',
  'Flower collecting and pressing',
  'Flying',
  'Footbag',
  'Foraging',
  'Foreign language learning',
  'Fossil hunting',
  'Freestyle football',
  'Fusilately (phonecard collecting)',
  'Gardening',
  'Genealogy',
  'Geocaching',
  'Ghost hunting',
  'Glassblowing',
  'Go',
  'Golfing',
  'Gongoozling',
  'Graffiti',
  'Gymnastics',
  'Handball',
  'Herping',
  'Hiking',
  'Homebrewing',
  'Hooping',
  'Houseplant care',
  'Hunting',
  'Hydroponics',
  'Ice hockey',
  'Ice skating',
  'Inline skating',
  'Insect collecting',
  'Jewelry making',
  'Jigsaw puzzles',
  'Jogging',
  'Judo',
  'Juggling',
  'Jukskei',
  'Kabaddi',
  'Kart racing',
  'Kayaking',
  'Kite flying',
  'Kitemaking',
  'Kitesurfing',
  'Knitting',
  'Lace making',
  'Lacrosse',
  'Lapidary',
  'LARPing',
  'Laser tag',
  'Lego building',
  'Letterboxing',
  'Listening to music',
  'Lotology (lottery ticket collecting)',
  'Machining',
  'Macrame',
  'Magic',
  'Mahjong',
  'Manga collecting',
  'Marbles',
  'Martial arts',
  'Metal detecting',
  'Meteorology',
  'Microscopy',
  'Mineral collecting',
  'Model aircraft',
  'Modeling',
  'Motor sports',
  'Mountain biking',
  'Mountaineering',
  'Movie memorabilia collecting',
  'Mushroom hunting/mycology',
  'Netball',
  'Nordic skating',
  'Notaphily (banknote collecting)',
  'Orienteering',
  'Origami',
  'Paintball',
  'Painting',
  'Parkour',
  'Photography',
  'Playing musical instruments',
  'Poker',
  'Polo',
  'Pottery',
  'Puzzles',
  'Quilting',
  'Racquetball',
  'Radio-controlled car racing',
  'Rafting',
  'Rappelling',
  'Reading',
  'Record collecting',
  'Recreational drug use',
  'Rock balancing',
  'Rock climbing',
  'Roller derby',
  'Roller skating',
  'Rugby',
  'Rugby league football',
  'Running',
  'Sailing',
  'Sand art',
  'Scrapbooking',
  'Sculling or rowing',
  'Sculpting',
  'Scuba diving',
  'Sea glass collecting',
  'Seashell collecting',
  'Sewing',
  'Shooting',
  'Shooting sports',
  'Shopping',
  'Shortwave listening',
  'Singing',
  'Skateboarding',
  'Sketching',
  'Skiing',
  'Skimboarding',
  'Skydiving',
  'Slacklining',
  'Sledding',
  'Slot car racing',
  'Snowboarding',
  'Soapmaking',
  'Speed skating',
  'Squash',
  'Stamp collecting',
  'Stand-up comedy',
  'Stone collecting',
  'Stone skipping',
  'Surfing',
  'Swimming',
  'Table football',
  'Table tennis',
  'Taekwondo',
  'Tai chi',
  'Taxidermy',
  'Tennis',
  'Tour skating',
  'Trainspotting',
  'Triathlon',
  'Ultimate frisbee',
  'Urban exploration',
  'Vehicle restoration',
  'Video game collecting',
  'Video gaming',
  'Vintage cars',
  'Volleyball',
  'Watching movies',
  'Water sports',
  'Weightlifting',
  'Wood carving',
  'Woodworking',
  'Worldbuilding',
  'Wrestling',
  'Writing',
  'Yoga',
  'Yo-yoing'
];

export const seedInterests = async () => {
  console.log('Starting interests seed...');

  let created = 0;
  let skipped = 0;

  for (const name of interestsData) {
    const existing = await prisma.interest.findFirst({
      where: {
        name,
        deleted: false
      }
    });

    if (!existing) {
      await prisma.interest.create({
        data: { name }
      });
      created++;
    } else {
      skipped++;
    }
  }

  console.log(`Interests seed complete: ${created} created, ${skipped} skipped`);
};

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedInterests()
    .then(() => {
      console.log('Seed completed successfully');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Seed failed:', error);
      process.exit(1);
    });
}




